version: '3.4'

services:
  romrepo.service:
    image: ${DOCKER_REGISTRY-}romreposervice
    user: root # :(
    volumes:
      - vol_db_client:/app-db
      - //nas01/emulation:/app-userfiles:ro
    build:
      context: .
      dockerfile: RomRepo.service/Dockerfile
volumes:
  vol_db_client: