version: '3.4'

services:
  romrepo.service:
    image: ${DOCKER_REGISTRY-}romreposervice
    user: root # :(
    volumes:
      - vol_db_client:/app-db
      - vol_lib_client:/app-userfiles           # dest path must match with RomRepoHostedService.cs
    build:
      context: .
      dockerfile: RomRepo.service/Dockerfile
volumes:
  vol_db_client:

  vol_lib_client:
    driver_opts:
      type: cifs
      o: "username=romrepo,password=mrbjSt2L"
      device: "//nas01/emulation"
