// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RomRepo.console;

#nullable disable

namespace RomRepo.console.Migrations
{
    [DbContext(typeof(RomRepoContext))]
    partial class RomRepoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("RomRepo.console.Models.Core", b =>
                {
                    b.Property<int>("CoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileExtensions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SevenZipAsRom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ZipAsRom")
                        .HasColumnType("INTEGER");

                    b.HasKey("CoreID");

                    b.ToTable("Core");
                });
#pragma warning restore 612, 618
        }
    }
}
