version: '3.4'

services:
  romrepo.api:
    image: ${DOCKER_REGISTRY-}romrepoapi
    user: root # :(
    volumes:
      - vol_db_api:/db_api
    build:
      context: .
      dockerfile: RomRepo.api/Dockerfile
volumes:
  vol_db_api: