// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RomRepo.web.Server.DataAccess;

#nullable disable

namespace RomRepo.web.Server.Migrations
{
    [DbContext(typeof(RomRepoContext))]
    [Migration("20230817025349_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("RomRepo.web.Server.Models.Core", b =>
                {
                    b.Property<int>("CoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileExtensions")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FolderAsRom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<bool>("SevenZipAsRom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ZipAsRom")
                        .HasColumnType("INTEGER");

                    b.HasKey("CoreID");

                    b.ToTable("Cores");
                });

            modelBuilder.Entity("RomRepo.web.Server.Models.Rom", b =>
                {
                    b.Property<int>("RomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoreID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHack")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentRomID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StarRating")
                        .HasColumnType("INTEGER");

                    b.HasKey("RomID");

                    b.HasIndex("CoreID");

                    b.HasIndex("ParentRomID");

                    b.ToTable("Roms");
                });

            modelBuilder.Entity("RomRepo.web.Server.Models.Rom", b =>
                {
                    b.HasOne("RomRepo.web.Server.Models.Core", "Core")
                        .WithMany("Roms")
                        .HasForeignKey("CoreID");

                    b.HasOne("RomRepo.web.Server.Models.Rom", "ParentRom")
                        .WithMany()
                        .HasForeignKey("ParentRomID");

                    b.Navigation("Core");

                    b.Navigation("ParentRom");
                });

            modelBuilder.Entity("RomRepo.web.Server.Models.Core", b =>
                {
                    b.Navigation("Roms");
                });
#pragma warning restore 612, 618
        }
    }
}
